name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Create .env
      run: |
        echo 'DB_NAME=${{ secrets.DB_NAME }}' >> .env
        echo 'DB_USER=${{ secrets.DB_USER }}' >> .env
        echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env
        echo 'DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}' >> .env
      
    - name: Build Docker
      run: docker compose up --build -d
