name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
  steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Login to Docker Hub
      uses: docker/login-action@main
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build Docker
      run: docker compose up --build -d
