name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/wordpress:latest .
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest -f ./nginx/Dockerfile .

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/nginx:latest
          docker-compose -f /path/to/docker-compose.yml up -d
        EOF
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
